#!/bin/bash
set -eou pipefail

generate_dates_mac() {
  year=$1
  start=$(gdate -d $year-11-26 +'%Y%m%d')
  end=$(gdate -d $year-12-30 +'%Y%m%d')

  local result=()

  while [ $start -le $end ]; do
    result+=($(gdate -d $start +'%Y-%m-%d'))
    start=$(gdate -d "$start +1 day" +'%Y%m%d')
  done

  push_github $result
}

generate_dates_linux() {
  year=$1
  start=$(date -d $year-03-14 +'%Y%m%d')
  end=$(date -d $year-03-16 +'%Y%m%d')

  local result=()

  while [ $start -le $end ]; do
    result+=($(date -d $start +'%Y-%m-%d'))
    start=$(date -d "$start +1 day" +'%Y%m%d')
  done

  push_github_linux $result
}

push_github() {
  result=$1

  for d in ${result[@]}; do
    sed -i '' 's/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/'$d'/g' HISTORY.md
    perl -pi -e 's/(Incremented: )([0-9]+)/"Incremented: ".($2+1)/e' HISTORY.md
    git commit --date="$d" -am "'$d'" ; git push

  done
}

push_github_linux() {
  result=$1

  for d in ${result[@]}; do
    sed -i 's/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/'$d'/g' HISTORY.md
    perl -pi -e 's/(Incremented: )([0-9]+)/"Incremented: ".($2+1)/e' HISTORY.md
    git commit --date="$d" -am "'$d'" ; git push -f origin master

  done
}

#generate_dates_mac 2016
generate_dates_linux 2017

exit 0
