#!/usr/bin/env bash
set -eou pipefail

git pull

# If using Linux/Debian, use -i w/o -i '' notation; if OS X, use -i ''
if [[ $(uname -s) == 'Darwin' ]]; then
  gsed -i 's/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/'$(date +%Y-%m-%d)'/g'    README.md
  gsed -ri 's/(Incremented: )([0-9]+)/echo "Incremented: $((\2+1))"/ge' README.md
else
  sed -i 's/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/'$(date +%Y-%m-%d)'/g'     README.md
  sed -ri 's/(Incremented: )([0-9]+)/echo "Incremented: $((\2+1))"/ge'  README.md
fi

git commit -am "'$(date +%Y-%m-%d)'" && \
  git push && \
  curl -fsS --retry 3 "https://hchk.io/${healthchecks_io_github_ping}" >/dev/null
