#!/usr/bin/env bash
set -eou pipefail

# If using Linux/Debian, use -i w/o -i '' notation; if OS X, use -i ''
sed -i 's/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/'$(date +%Y-%m-%d)'/g' README.md
perl -pi -e 's/(Incremented: )([0-9]+)/"Incremented: ".($2+1)/e' README.md

git commit -am "'$(date +%Y-%m-%d)'" && \
  git push && \
  curl -fsS --retry 3 "https://hchk.io/${healthchecks_io_api_key}" >/dev/null
